### ISSUE TITLE
Parent linking TODO's

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus-service-to-service-correlation-poc#14]
Currently, I'm thinking of these TODO tasks (also documented in the code):
- [ ] Web API middleware should extract only last part of operation parent ID ( `Request-Id`: `|abc.def` should become `Parent ID`: `abc` in Application Insights, currently, it's `|abc.def`) (https://github.com/arcus-azure/arcus-service-to-service-correlation-poc/pull/13/files#diff-fb92c0f5cee4ab12e7f9150943d525590093b76916d4e94ba3949ed80a06dd3fR194)
- [ ] Application Insights Sink should differentiate between request and other types of telemetry when assigning correlation, the request telemetry needs the operation ID as it's telemetry ID, while the other types need the operation ID as parent ID.  (https://github.com/arcus-azure/arcus-service-to-service-correlation-poc/pull/13/files#diff-8ca727275995a3807a592ad7bd393c6044e1dc7db434516cda2ffd1d9bf40dd8R28)
- [ ] Message router should assign the correlation directly instead of via the `IMessageCorrelationInfoAccessor` because the Serilog enrichment happens at a later stage, outside the availability of the accessor. (https://github.com/arcus-azure/arcus-service-to-service-correlation-poc/pull/13/files#diff-baa446f63c0f3d982de91acaf8252216a3256b92bdc9a53d66a7e8c42f7901dbR214)
- [ ] I also think that the message pump will have to generate an operation ID if there's no available. Currently, the Web API middleware also generate one, but the POC currently generate one during the dependency tracking (so before the actual call to Azure Service Bus).

_Originally posted by @stijnmoreels in https://github.com/arcus-azure/arcus-service-to-service-correlation-poc/issues/13#issuecomment-1157321574_
